name: gym 
channels:
    - anaconda
    - conda-forge #https://conda-forge.org/
    - pytorch
    - fastai
dependencies:
    - python=3.7
    - nodejs
    - fastai
    - cuda92
    - pytorch
    - torchvision
    - pytorch-gpu
    - tensorflow-gpu
    - dataclasses
    - pandas
    - numpy
    - scikit-learn
    - scikit-image
    - scipy
    - ipywidgets
    - dask
    - distributed
    - seaborn
    - jupyter #notebook
    - jupyterlab
    - beakerx
    - beakerx_tabledisplay
    - fastprogress
    - tqdm
    - requests
    - pip
    - pip:
        - nvidia-ml-py3
        - jupyter_contrib_nbextensions
        - jupyter_nbextensions_configurator
        - autopep8
        - git+https://github.com/dask/dask.git
        - git+https://github.com/dask/distributed.git
